# Created by Crt Vavros, copyright © 2022 ZeroPass. All rights reserved.
name: dmrtd
description: Dart implementation of ICAO Doc 9303 MRTD, created by ZeroPass
version: 1.4.4

environment:
  sdk: ^3.5.0

dependencies:
  archive: ^4.0.7
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.6
  expandable: ^5.0.1
  fixnum: ^1.1.1
  flutter_nfc_kit: ^3.6.0
  logging: ^1.3.0
  meta: ^1.17.0
  tripledes_nullsafety: ^1.0.3
  pointycastle: ^4.0.0

dev_dependencies:
  flutter:      # needed for flutter_nfc_kit
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_test: # needed for flutter_nfc_kit
    sdk: flutter
  test: ^1.25.15

dependency_overrides:
  meta: ^1.17.0